Connection reuse
For read onyl requests the connection has to be closed and not reused as it no longer can
be set into commit mode.

With psycopg2 driver this is indicated with:

```
psycopg2.ProgrammingError: set_session cannot be used inside a transaction
```